name: Github Workflow Experiment 
run-name: ${{ github.actor}} learning git workflows by own project
on: [push , workflow_dispatch]
jobs:
  Excel-Operations:
    runs-on:
     labels: automation
    steps:
      - name: Repo Setup
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm ci
      - name: Run Test Scripts
        run: npm test 
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
          

      - name: Check Connected Devices
        run: flutter emulators --launch Pixel 7 Pro
      
      - name: Launch application on Connected Device
        run: npm run wdio
      
      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: path/to/screenshots-or-logs

      - name: Stop Android emulator
        if: always()
        run: adb -s emulator-5554 emu kill
    


  
