name: Github Workflow Experiment 
run-name: ${{ github.actor}} learning git workflows by own project
on: [push, workflow_dispatch]
jobs:
  Excel-Operations:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Setup
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm ci
      - name: Run Test Scripts
        run: npm test  
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - uses: actions/checkout@v4
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      - name: Setting up java  gradlew
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - run: ./gradlew build --no-daemon
      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: arm64-v8a
          script: ./gradlew connectedCheck
      - name: Check Connected Devices
        run: adb devices
    


  
