name: Github Workflow Experiment 
run-name: ${{ github.actor}} learning git workflows by own project
on: [workflow_dispatch]
jobs:
  Excel-Operations:
    runs-on:
     labels: automation
    steps:
      - name: Repo Setup
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm ci
      - name: Run Test Scripts
        run: npm test 
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4
      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          script: ./gradlew connectedCheck
          profile: pixel_6_pro
      - name: Check Connected Devices
        run: adb devices
    


  
